name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # See also https://github.com/flatpak/flatpak-github-actions
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: flatpak gettext # FIXME use flatpak sdk for msgfmt tests
          version: 1.0

      - name: Cache Flatpak dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/flatpak
          key: 45beta

      - run: make ci

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Extensions
        run: |
          flatpak --system install -y --noninteractive org.freedesktop.Sdk.Extension.vala/x86_64/23.08 org.freedesktop.Sdk.Extension.rust-stable/x86_64/23.08 org.freedesktop.Sdk.Extension.llvm16/x86_64/23.08
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: workbench.flatpak
          repository-name: flathub-beta
          manifest-path: build-aux/re.sonny.Workbench.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
